name: First Github Workflow

on: push

jobs: 
  my-first-jobs: 
    runs-on: ubuntu-latest

    steps: 
    - name: Print a message 
      run: echo "Hello from my first github action"

    - name: Checking linting
      run: echo "Linting checking...."
